spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/demo_db?schema=public
    username: postgres
    password: 1234
  liquibase:
    changeLog: classpath:db/changelog/db.changelog-master.yaml

logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG
